/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf4 {
    #[serde(rename = "FailedCreateUnsignedTx")]
    pub failed_create_unsigned_tx: String,
}

impl ApiErrorOneOf4 {
    pub fn new(failed_create_unsigned_tx: String) -> ApiErrorOneOf4 {
        ApiErrorOneOf4 {
            failed_create_unsigned_tx,
        }
    }
}
