/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LockFundsRequest {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(
        rename = "estimated_output_size",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub estimated_output_size: Option<Option<i32>>,
    #[serde(rename = "fee_per_gram", skip_serializing_if = "Option::is_none")]
    pub fee_per_gram: Option<i64>,
    #[serde(
        rename = "idempotency_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub idempotency_key: Option<Option<String>>,
    #[serde(
        rename = "num_outputs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub num_outputs: Option<Option<i32>>,
    #[serde(
        rename = "seconds_to_lock_utxos",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seconds_to_lock_utxos: Option<Option<i64>>,
}

impl LockFundsRequest {
    pub fn new(amount: i64) -> LockFundsRequest {
        LockFundsRequest {
            amount,
            estimated_output_size: None,
            fee_per_gram: None,
            idempotency_key: None,
            num_outputs: None,
            seconds_to_lock_utxos: None,
        }
    }
}
