/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LockFundsResponse {
    #[serde(rename = "fee_with_change")]
    pub fee_with_change: i64,
    #[serde(rename = "fee_without_change")]
    pub fee_without_change: i64,
    #[serde(rename = "requires_change_output")]
    pub requires_change_output: bool,
    #[serde(rename = "total_value")]
    pub total_value: i64,
    #[serde(rename = "utxos")]
    pub utxos: Vec<serde_json::Value>,
}

impl LockFundsResponse {
    pub fn new(
        fee_with_change: i64,
        fee_without_change: i64,
        requires_change_output: bool,
        total_value: i64,
        utxos: Vec<serde_json::Value>,
    ) -> LockFundsResponse {
        LockFundsResponse {
            fee_with_change,
            fee_without_change,
            requires_change_output,
            total_value,
            utxos,
        }
    }
}
